server:
  port: 8080
spring:
  application:
    name: ${MOVIE_CATALOG:movie-catalog}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true
        order_inserts: true
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-db2?serverTimezone=UTC&useSSL=false
    username: postgres
    password: 1234




